# Generated by Django 4.0.2 on 2022-02-06 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('link_info', models.CharField(blank=True, default=None, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_client.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('paid_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_client.asset')),
                ('filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio_client.filter')),
            ],
        ),
    ]
